version: '0.1'
services:
  minio:
    container_name: minio-s3
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    volumes:
      - minio_data:/data
    ports:
      - '9000:9000' # S3 API port
      - '9001:9001' # Web console port
    healthcheck:
      test: 'curl -f http://localhost:9000/minio/health/live || exit 1'
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 5s

  database:
    container_name: database
    image: postgres:17.4
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user123
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:
