import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { NavigationBar } from './components/NavigationBar';
import { PageContainer } from './components/generic/PageContainer';
import { ClientSideProviders } from './client.providers';
import { BreadcrumbNavigation } from './components/BreadcrumbNavigation';
import { Footer } from './components/generic/Footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientSideProviders>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <NavigationBar>
            <PageContainer>
              <BreadcrumbNavigation />
              {children}
            </PageContainer>
            <Footer />
          </NavigationBar>
        </body>
      </html>
    </ClientSideProviders>
  );
}
