import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '../globals.css';
import { NavigationBar } from '../components/NavigationBar';
import { PageContainer } from '../components/library/PageContainer';
import { ClientSideProviders } from '../client.providers';
import { BreadcrumbNavigation } from '../components/BreadcrumbNavigation';
import { Footer } from '../components/library/Footer';
import { Separator } from '../components/library/Separator';
import { notFound } from 'next/navigation';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { routing } from '@/i18n/routing';
import { getMessages } from 'next-intl/server';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    return notFound();
  }
  const messages = await getMessages();

  return (
    <ClientSideProviders>
      <html lang={locale}>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <NextIntlClientProvider messages={messages}>
            <NavigationBar>
              <PageContainer>
                <BreadcrumbNavigation />
                {children}
              </PageContainer>
              <Separator orientation="horizontal" variant="primary" />
              <Footer text="© 2025 Acasuca, BIT ROCKET" imageSrc="/content/images/logo.svg" imageAlt="logo" />
            </NavigationBar>
          </NextIntlClientProvider>
        </body>
      </html>
    </ClientSideProviders>
  );
}
